using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Resources;

namespace Blog.Models
{
    public class Personal
    {
        // Primary Key Auto Generated by DB and not display in forms
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [HiddenInput(DisplayValue = false)]
        public Guid Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(Res), ErrorMessageResourceName = "RequiredFirstName")]
        [Display(Name = "Firstname", ResourceType = typeof(Res))]
        public string Firstname { get; set; }

        [Required(ErrorMessageResourceType = typeof(Res), ErrorMessageResourceName = "RequiredLastName")]
        [Display(Name = "Lastname", ResourceType = typeof(Res))]
        public string Lastname { get; set; }

        [Required(ErrorMessageResourceType = typeof(Res), ErrorMessageResourceName = "RequiredTitle")]
        [Display(Name = "Title", ResourceType = typeof(Res))]
        public string Title { get; set; }

        // Textarea
        [Required(ErrorMessageResourceType = typeof(Res), ErrorMessageResourceName = "RequiredDescription")]
        [Display(Name = "Description", ResourceType = typeof(Res))]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}